// Package model provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package model

// Address defines model for Address.
type Address struct {
	City    *string `json:"city,omitempty"`
	Country *string `json:"country,omitempty"`
	Line1   *string `json:"line1,omitempty"`
	Line2   *string `json:"line2,omitempty"`

	// Location Data returned from the Location service
	Location *Location `json:"location,omitempty"`
	State    *string   `json:"state,omitempty"`

	// TimezoneName Name of the timezone following the IANA standard (https://www.iana.org/time-zones)
	TimezoneName *string `json:"timezoneName,omitempty"`
	ZipCode      *string `json:"zipCode,omitempty"`
}

// Location Data returned from the Location service
type Location struct {
	AddressNumber *string `json:"addressNumber,omitempty"`
	Country       *string `json:"country,omitempty"`

	// Geocode Geocode of address (format lat,lon)
	Geocode      *string `json:"geocode,omitempty"`
	Municipality *string `json:"municipality,omitempty"`
	PostalCode   *string `json:"postalCode,omitempty"`
	Region       *string `json:"region,omitempty"`
	Street       *string `json:"street,omitempty"`
	SubRegion    *string `json:"subRegion,omitempty"`
}

// Restaurant defines model for Restaurant.
type Restaurant struct {
	Address *Address `json:"address,omitempty"`

	// Description Description of the restaurant
	Description *string `json:"description,omitempty"`

	// Id ID of the restaurant
	Id *string `json:"id,omitempty"`

	// Name Name of the restaurant
	Name        string  `json:"name"`
	PhoneNumber *string `json:"phoneNumber,omitempty"`
}

// RestaurantId defines model for RestaurantId.
type RestaurantId = string

// N404Error defines model for 404Error.
type N404Error struct {
	Message *string `json:"message,omitempty"`
}

// PostJSONRequestBody defines body for Post for application/json ContentType.
type PostJSONRequestBody = Restaurant

// PostRestaurantIdJSONRequestBody defines body for PostRestaurantId for application/json ContentType.
type PostRestaurantIdJSONRequestBody = Restaurant
